// ============================================================
//  English Challenge – Question Bank
//  Standard 4 Level | Format: { q, o: [4 options], a }
//
//  To refresh questions:
//  1. Edit this file directly — add, remove, or replace entries
//  2. Keep the same structure: q (question), o (options array), a (correct answer)
//  3. The answer in "a" must exactly match one of the strings in "o"
//  4. Save the file and reload index.html in the browser
// ============================================================

const questions = [
    { q: "Which word is a noun?", o: ["run", "happy", "book", "quickly"], a: "book" },
    { q: "I have ___ apple.", o: ["a", "an", "the", "any"], a: "an" },
    { q: "The cat is sleeping ___ the mat.", o: ["in", "on", "at", "with"], a: "on" },
    { q: "What is the past tense of 'go'?", o: ["goed", "gone", "went", "goes"], a: "went" },
    { q: "A person who flies a plane is a ___.", o: ["doctor", "pilot", "teacher", "farmer"], a: "pilot" },
    { q: "Which is the opposite of 'hot'?", o: ["warm", "cold", "fire", "sun"], a: "cold" },
    { q: "The plural of 'mouse' is ___.", o: ["mouses", "mice", "mouse", "meese"], a: "mice" },
    { q: "She ___ to school every day.", o: ["go", "goes", "is going", "went"], a: "goes" },
    { q: "A place where you borrow books.", o: ["shop", "park", "library", "canteen"], a: "library" },
    { q: "Which word means 'very big'?", o: ["tiny", "small", "huge", "little"], a: "huge" },
    { q: "The sun ___ in the east.", o: ["rise", "rises", "rose", "risen"], a: "rises" },
    { q: "We use our ___ to see.", o: ["ears", "nose", "eyes", "hands"], a: "eyes" },
    { q: "A cow says '___'.", o: ["oink", "meow", "moo", "baa"], a: "moo" },
    { q: "Which is NOT a fruit?", o: ["apple", "banana", "carrot", "orange"], a: "carrot" },
    { q: "I write with a ___.", o: ["chair", "pen", "spoon", "bed"], a: "pen" },
    { q: "He is ___ an ice cream.", o: ["eat", "eats", "eating", "ate"], a: "eating" },
    { q: "The opposite of 'fast' is ___.", o: ["quick", "run", "slow", "stop"], a: "slow" },
    { q: "A ___ has eight legs.", o: ["bee", "ant", "spider", "fly"], a: "spider" },
    { q: "We sleep in the ___.", o: ["kitchen", "bathroom", "bedroom", "living room"], a: "bedroom" },
    { q: "The sky is ___.", o: ["green", "blue", "red", "yellow"], a: "blue" },
    { q: "Which month has 28 or 29 days?", o: ["January", "February", "March", "April"], a: "February" },
    { q: "A baby dog is a ___.", o: ["kitten", "puppy", "cub", "chick"], a: "puppy" },
    { q: "They ___ playing football now.", o: ["is", "am", "are", "was"], a: "are" },
    { q: "The synonym of 'happy' is ___.", o: ["sad", "angry", "joyful", "tired"], a: "joyful" },
    { q: "What do you do with a book?", o: ["eat", "drink", "read", "play"], a: "read" },
    { q: "A lion is a ___ animal.", o: ["tame", "pet", "wild", "farm"], a: "wild" },
    { q: "The plural of 'leaf' is ___.", o: ["leafs", "leaves", "leafe", "leafes"], a: "leaves" },
    { q: "I ___ a student.", o: ["is", "am", "are", "be"], a: "am" },
    { q: "Which word is a verb?", o: ["car", "jump", "red", "slowly"], a: "jump" },
    { q: "The opposite of 'day' is ___.", o: ["morning", "sun", "night", "evening"], a: "night" },
    { q: "A baker bakes ___.", o: ["clothes", "bread", "shoes", "furniture"], a: "bread" },
    { q: "We smell with our ___.", o: ["eyes", "ears", "mouth", "nose"], a: "nose" },
    { q: "Yesterday, I ___ to the park.", o: ["go", "goes", "went", "gone"], a: "went" },
    { q: "Which of these is a vegetable?", o: ["mango", "potato", "grape", "pear"], a: "potato" },
    { q: "A hospital is a place for ___ people.", o: ["hungry", "sick", "happy", "rich"], a: "sick" },
    { q: "The antonym of 'beautiful' is ___.", o: ["pretty", "lovely", "ugly", "nice"], a: "ugly" },
    { q: "The cat chased the ___.", o: ["mouse", "house", "cloud", "flower"], a: "mouse" },
    { q: "I will ___ my homework tomorrow.", o: ["do", "did", "done", "does"], a: "do" },
    { q: "A car has four ___.", o: ["wings", "wheels", "doors", "windows"], a: "wheels" },
    { q: "What is the sound a duck makes?", o: ["oink", "quack", "chirp", "bark"], a: "quack" },
    { q: "Choose the correct spelling.", o: ["elefant", "elephant", "elephent", "elyphant"], a: "elephant" },
    { q: "The children ___ in the field.", o: ["plays", "play", "is playing", "am playing"], a: "play" },
    { q: "Water is for ___.", o: ["eating", "drinking", "sleeping", "running"], a: "drinking" },
    { q: "The opposite of 'full' is ___.", o: ["heavy", "empty", "many", "complete"], a: "empty" },
    { q: "A fish swims in the ___.", o: ["sky", "forest", "water", "desert"], a: "water" },
    { q: "Which is a piece of furniture?", o: ["plate", "comb", "table", "shirt"], a: "table" },
    { q: "She ___ a beautiful song yesterday.", o: ["sing", "sings", "sang", "sung"], a: "sang" },
    { q: "The capital of Malaysia is ___.", o: ["Penang", "Johor Bahru", "Kuala Lumpur", "Kuching"], a: "Kuala Lumpur" },
    { q: "A week has ___ days.", o: ["five", "six", "seven", "eight"], a: "seven" },
    { q: "The plural of 'child' is ___.", o: ["childs", "childrens", "children", "childes"], a: "children" },
    { q: "Look at ___ beautiful rainbow!", o: ["a", "an", "that", "those"], a: "that" },
    { q: "Which is a synonym for 'small'?", o: ["big", "large", "little", "wide"], a: "little" },
    { q: "A pilot flies an ___.", o: ["aeroplane", "autocar", "aquarium", "artship"], a: "aeroplane" },
    { q: "The moon shines at ___.", o: ["day", "noon", "night", "morning"], a: "night" },
    { q: "I am thirsty. I need some ___.", o: ["food", "water", "sleep", "air"], a: "water" },
    { q: "He kicked the ball ___ his foot.", o: ["with", "by", "for", "from"], a: "with" },
    { q: "Past tense of 'eat' is ___.", o: ["eated", "eaten", "ate", "eat"], a: "ate" },
    { q: "An apple a day keeps the ___ away.", o: ["teacher", "friend", "doctor", "postman"], a: "doctor" },
    { q: "The opposite of 'strong' is ___.", o: ["brave", "weak", "big", "heavy"], a: "weak" },
    { q: "A ___ gives us wool.", o: ["cow", "goat", "sheep", "hen"], a: "sheep" },
    { q: "Which is the correct sentence?", o: ["She is a girl beautiful.", "She a girl is beautiful.", "She is a beautiful girl.", "A beautiful girl she is."], a: "She is a beautiful girl." },
    { q: "I bought ___ new shoes.", o: ["a", "some", "any", "one"], a: "some" },
    { q: "A dolphin is a type of ___.", o: ["bird", "insect", "mammal", "reptile"], a: "mammal" },
    { q: "The book is ___ the table.", o: ["in", "on", "under", "over"], a: "on" },
    { q: "I can ___ very fast.", o: ["ran", "run", "runs", "running"], a: "run" },
    { q: "Choose the silent letter in 'knife'.", o: ["k", "n", "i", "f"], a: "k" },
    { q: "Which is an adjective?", o: ["school", "happily", "beautiful", "play"], a: "beautiful" },
    { q: "We celebrate Hari Raya ___ Syawal.", o: ["in", "on", "at", "during"], a: "in" },
    { q: "The ___ is the king of the jungle.", o: ["tiger", "lion", "elephant", "monkey"], a: "lion" },
    { q: "What is the opposite of 'start'?", o: ["begin", "go", "finish", "open"], a: "finish" },
    { q: "The past tense of 'see' is ___.", o: ["seed", "saw", "seen", "seeing"], a: "saw" },
    { q: "A person who teaches is a ___.", o: ["teacher", "student", "player", "dancer"], a: "teacher" },
    { q: "There are twelve ___ in a year.", o: ["days", "weeks", "months", "hours"], a: "months" },
    { q: "A baby cat is called a ___.", o: ["puppy", "chick", "kitten", "cub"], a: "kitten" },
    { q: "Which word rhymes with 'cat'?", o: ["hat", "cot", "cut", "car"], a: "hat" },
    { q: "He ___ television every evening.", o: ["watch", "watches", "watching", "watched"], a: "watches" },
    { q: "The plural of 'woman' is ___.", o: ["womans", "women", "womens", "womanes"], a: "women" },
    { q: "My father is a doctor. ___ works in a hospital.", o: ["She", "He", "It", "They"], a: "He" },
    { q: "The sun is very ___ today.", o: ["hot", "cold", "wet", "dark"], a: "hot" },
    { q: "Which of these is a liquid?", o: ["rock", "milk", "bread", "ice"], a: "milk" },
    { q: "I use a ___ to call my friend.", o: ["book", "television", "phone", "radio"], a: "phone" },
    { q: "The opposite of 'rich' is ___.", o: ["wealthy", "poor", "happy", "sad"], a: "poor" },
    { q: "A bicycle has ___ wheels.", o: ["one", "two", "three", "four"], a: "two" },
    { q: "The bird is flying ___ the sky.", o: ["on", "at", "in", "under"], a: "in" },
    { q: "Can you help ___?", o: ["I", "my", "me", "mine"], a: "me" },
    { q: "She ___ her teeth every morning.", o: ["brush", "brushes", "brushed", "brushing"], a: "brushes" },
    { q: "A firefighter puts out ___.", o: ["water", "fire", "wind", "sand"], a: "fire" },
    { q: "The synonym of 'look' is ___.", o: ["see", "hear", "smell", "taste"], a: "see" },
    { q: "We live on Planet ___.", o: ["Mars", "Venus", "Earth", "Jupiter"], a: "Earth" },
    { q: "The national flower of Malaysia is the ___.", o: ["rose", "orchid", "hibiscus", "sunflower"], a: "hibiscus" },
    { q: "Which of these can fly?", o: ["cat", "dog", "bird", "fish"], a: "bird" },
    { q: "The opposite of 'short' is ___.", o: ["small", "long", "thin", "narrow"], a: "long" },
    { q: "I am going ___ the market.", o: ["to", "at", "in", "for"], a: "to" },
    { q: "The plural of 'man' is ___.", o: ["mans", "menes", "men", "mens"], a: "men" },
    { q: "The turtle walks very ___.", o: ["fast", "quickly", "slowly", "rapidly"], a: "slowly" },
    { q: "Which animal lives in the sea?", o: ["monkey", "whale", "lion", "zebra"], a: "whale" },
];
